"""The provider boundary; planning and ownership checks stay outside it."""

import subprocess
from collections.abc import Mapping, Sequence
from typing import BinaryIO, Protocol

from nixant.models import MachineSpec, MachineState, MountSpec, Snapshot
from nixant.planner import Change


class Provider(Protocol):
    def inspect(self, name: str) -> MachineState | None: ...
    def find(self, metadata: Mapping[str, str]) -> list[MachineState]: ...
    def create(self, spec: MachineSpec, metadata: Mapping[str, str]) -> None: ...
    def start(self, name: str) -> None: ...
    def stop(self, name: str, *, force: bool = False) -> None: ...
    def restart(
        self, name: str, *, force: bool = False, timeout: float | None = None
    ) -> None: ...
    def destroy(self, name: str) -> None: ...
    def set_metadata(self, name: str, metadata: Mapping[str, str]) -> None: ...
    def apply(self, name: str, change: Change) -> None: ...
    def check_quota(self, pool: str | None) -> None: ...
    def snapshot_create(self, name: str, snapshot: str) -> None: ...
    def snapshot_list(self, name: str) -> list[Snapshot]: ...
    def snapshot_delete(self, name: str, snapshot: str) -> None: ...
    def snapshot_restore(self, name: str, snapshot: str) -> None: ...
    def verify_mounts(self, name: str, mounts: Sequence[MountSpec]) -> None: ...
    def run(
        self,
        name: str,
        argv: list[str],
        *,
        user: str | None = None,
        cwd: str | None = None,
        stdin: BinaryIO | None = None,
        capture: bool = False,
        capture_stderr: bool = False,
        tee_stderr: bool = False,
        check: bool = True,
        timeout: float | None = None,
    ) -> subprocess.CompletedProcess[bytes]: ...
    def exec_argv(
        self, name: str, argv: list[str], *, user: str, cwd: str
    ) -> list[str]: ...
